package com.auction.enums;

/**
 * Enum định nghĩa các loại hành động/mã lệnh mạng trao đổi giữa Client và Server.
 */
public enum ActionType {
    
    LOGIN,
    REGISTER,
    LOGOUT,
    CREATE_ITEM,
    UPDATE_ITEM,
    SELLER_DELETE_ITEM,
    GET_SELLER_ITEMS,
    GET_ITEM_DETAIL,
    GET_ACTIVE_AUCTIONS,
    GET_AUCTION_DETAIL,
    CREATE_AUCTION,
    PLACE_BID,
    SELLER_CANCEL_AUCTION,
    GET_SELLER_AUCTIONS,
    UPDATE_AUCTION,
    BID_UPDATE,
    TIME_UPDATE,
    STATUS_UPDATED,
    FORCE_LOGOUT,
    GET_AUCTION_BID_HISTORY,
    GET_MY_BID_HISTORY,

    AUCTION_SUBSCRIBED,

    AUCTION_UNSUBSCRIBED,

    LIVE_ENTERED,

    LIVE_EXITED,

    GET_USER_PROFILE,
    UPDATE_PROFILE,
    UPDATE_PASSWORD,
    DEPOSIT_MONEY,
    WITHDRAW_MONEY,
    CMD_ADMIN_GET_USERS,
    CMD_ADMIN_LOCK_USER,
    CMD_ADMIN_GET_LOGS,
    CMD_ADMIN_CANCEL_AUCTION,
    CMD_ADMIN_DELETE_ITEM,
    CMD_ADMIN_GET_ITEMS,
    CMD_ADMIN_GET_AUCTIONS,
    PING,
    SETUP_AUTO_BID,
    CANCEL_AUTO_BID,
    WALLET_UPDATE,
    AUTO_BID_DEACTIVATED,
}
